### ISSUE TITLE
Think about how these will work offline

### ISSUE THREAD

**Issue by ewels** [nf-core/configs#1]
A point I thought of earlier today is that we need to think about how these configs will work offline.

It could be simply that we update the `nf-core download` command to also always download this repo. That may be sufficient.

**Comment by drpatelh** [comment]
@micans actually bought this up after the Hackathon. I forgot to mention it.

Is `nf-core download` run everytime we run an nf-core pipeline with nextflow? Im just trying to work out whether we will get a use case where the installations/executions are completely separate.

**Comment by ewels** [comment]
No, it's a separate subcommand that is designed to be run on an _online_  system to make a nice simple folder of files ready to be transferred to the offline system. See https://github.com/nf-core/tools#downloading-pipelines-for-offline-use

Note that we could be extra clever in this situation and do extra stuff, such as bundling these configs into the pipeline directory and adding a config line to set a relative base import "URL" (path)?
