### ISSUE TITLE
CPUs / Memory scaling factors

### ISSUE THREAD

**Issue by ewels** [nf-core/configs#114]
On our UPPMAX clusters, nodes have a given scaling factor where a certain amount of memory is allowed per CPU. Previously, if you submitted a job which requests both CPUs and memory and these values didn't match the scaling factor, SLURM would just silently bump up whichever value was needed to make the scaling factor match. However, apparently this behaviour has now changed and now SLURM simply refuses to run these jobs with the error ` Requested node configuration is not available`.

Instead of writing new configuration files for every pipeline for each UPPMAX cluster, I wonder if we can instead just specify the relevant scaling factor (memory per cpu) for each UPPMAX cluster and adjust the job requests before submission to the cluster.

We already run job requirements through the [`check_max`](https://github.com/nf-core/atacseq/blob/fa1e3f8993cd20e249b9df09d29c5498eff311d2/nextflow.config#L165-L196) function, so I perhaps we could tie in to this somehow from the institutional configs? Then run a custom function to round up either the cpus or memory as needed.

The main problem I can see with this is that the `check_max` function takes one resource type at a type. Here, we need to know both the cpus and memory simultaneously. As such I think that this is going to require new modifications to every pipeline 😞

**Comment by ewels** [comment]
@pditommaso - is there any way to hook in to Nextflow itself to handle this `memory-per-cpu` issue? Nextflow already knows all of the final job resource values prior to job submission, so a solution within nextflow itself would be the most elegant and fool-proof method if possible.

**Comment by ewels** [comment]
NB: Current node configuration for UPPMAX Rackham if useful: (thanks @pontus)

```console
[pontusf-test@rackham1 ~]$ scontrol show part=core
PartitionName=core
   AllowGroups=ALL AllowAccounts=ALL AllowQos=ALL
   AllocNodes=ALL Default=YES QoS=N/A
   DefaultTime=00:01:00 DisableRootJobs=YES ExclusiveUser=NO GraceTime=0 Hidden=NO
   MaxNodes=1 MaxTime=10-00:00:00 MinNodes=0 LLN=NO MaxCPUsPerNode=UNLIMITED
   Nodes=r[33-336,338,340,342-482]
   PriorityJobFactor=1 PriorityTier=1 RootOnly=NO ReqResv=NO OverSubscribe=NO
   OverTimeLimit=NONE PreemptMode=OFF
   State=UP TotalCPUs=8940 TotalNodes=447 SelectTypeParameters=NONE
   JobDefaults=(null)
   DefMemPerCPU=6400 MaxMemPerNode=UNLIMITED
```

**Comment by pditommaso** [comment]
Is not `memory = { task.cpus * <mem> }` enough ?

**Comment by ewels** [comment]
That would be one way of doing it. But that would then assume that all systems have the same concept of a scaling factor like this, and we would need to rewrite every config for every pipeline... I quite like the granularity of being able to specify cpus and memory separately personally.

**Comment by drpatelh** [comment]
What if we add a `--mem_per_cpu` option to the template? Could use that to calculate and override  memory if specified.

This is exactly why I reduced the memory in base.config in the template to multiples of 7 because that's what we have at the Crick.

You have 6GB on Uppmax?

Problem with that is that it won't work until pipelines are synced with the template.

Or we find a way to add it to the Institutional configs as you suggested @ewels.

**Comment by drpatelh** [comment]
Will something like the below work if specified in an Institutional config?

```
process {
  memory = task.cpus * 6
}
```

**Comment by pontus** [comment]
I think it can be expected these values to vary wildly - a common/simple approach is to divide memory available in compute nodes with the number of cores, and that gives three different values at UPPMAX alone nodes with the same physical memory size (although in one case, there's OpenStack stealing some memory instead).

And it gets a lot worse, just looking at possible mem/core combinations (128 Gbyte for 64 cores?), ignoring possibilities for heterogeneous nodes and different policies.

There are a few things where I'm not sure about the design philosophy here; 

* How much should be specified, how much is "allowed" to be calculated?
  * It's likely quite difficult to calculate values that are optimal and may be confusing for the user.

  * But as needed values likely will differ, not calculating means the user (or pipeline manager) needs
    to do so, which may raise the difficulty level substantially.

    Having it user-specified makes it more likely to have issues with pipeline upgrades as it
    often feels easier to change the pipeline code than figure out how to write your custom
    configuration to fix what's needed.

* How separate are different nextflow components?

  These are particulars for job schedulers (or cloud provider interface), so it should likely be handled
  in these components, but do/should they know enough about the processes to make accurate 
  decisions (or give good warnings).


Specifically for slurm, I think it should be possible to at least get the defmempercore for the selected partition and warn the user they may have issues if the amount of memory requested exceeds requested_cores*defmempercore (or possibly have a flag to allow it to add extra cores "automatically" if it can).

Something such, while hackish (not a good) solution might be helpful for the users at least. I'm unsure to what degree the possible complexities are worth taking on.

**Comment by HaiyangDu** [comment]
？

**Comment by jfy133** [comment]
I will shut this  next week as I expect after 4 years it's out of date, unless  you think otherwise @ewels ?

**Comment by ewels** [comment]
Yeah fine to close. I don't really remember it at all, so presumably it either wasn't a bad problem or it ceased being a problem at some point 🤔
