### ISSUE TITLE
Make regular releases of this repository

### ISSUE THREAD

**Issue by apeltzer** [nf-core/configs#18]
Some users that were using pipelines already using the centralized configs repository had issues after yesterdays functional update in here:

```
N E X T F L O W  ~  version 19.01.0
Launching `nf-core/rnafusion` [sleepy_goldstine] - revision: b2fb212d31 [dev]
ERROR ~ Unable to parse config file: '/home-link/qeaga01/.nextflow/assets/nf-core/rnafusion/nextflow.config'

 Illegal character in scheme name at index 0: %5B:%5D/conf/cfc.config


-- Check '.nextflow.log' file for details
```

This affected all pipelines already using the centralized configs, as the `${params.custom_config_base}` isn't defined in the previous version of this repository, thus making all changes in this repository propagate to eager, rnaseq, ampliseq, rnafusion, hlatyping, methylseq (?)and potentially others as well. 

We should maybe consider having something in nf-core/tools that checks that the pipeline releases are pinning against a specific tag (can be something fixed other than latest), thus making any changes permanent. Thoughts on this?

**Comment by apeltzer** [comment]
Opened an issue in nf-core/tools for this as well https://github.com/nf-core/tools/issues/273

**Comment by apeltzer** [comment]
And of course, do regular releases here as well - that can then be downloaded on demand / pinned against 👍

**Comment by ewels** [comment]
As discussed elsewhere, we should not pin configs in pipelines. But we (me in this case) should be more careful not to break stuff. CI is the main way to do this.

**Comment by ewels** [comment]
Closing this issue, as releases here are fine but won't really affect how stuff should run at all.

**Comment by apeltzer** [comment]
:+1:
