### ISSUE TITLE
cambridge profile not in here

### ISSUE THREAD

**Issue by maxozo** [nf-core/configs#260]
hi, while you have a Cambridge profile listed under https://github.com/nf-core/configs#documentation 
and is in the https://github.com/nf-core/configs/blob/master/conf/cambridge.config it is not added under the https://github.com/nf-core/configs/blob/master/nfcore_custom.config which subsequently gives an error:
`Unknown configuration profile: 'cambridge'`
could you please add it.

**Comment by maxulysse** [comment]
@maxozo It should be working now

**Comment by maxozo** [comment]
Thank you!
