### ISSUE TITLE
Sarek on Irma breaks with new uppmax.config

### ISSUE THREAD

**Issue by parlundin** [nf-core/configs#291]
When running Sarek on IRMA with updated uppmax.config 

```
Command output:
sbatch: error: Batch job submission failed: Invalid feature specification.
```
`#SBATCH -A ngi2016003  -p node -C mem512GB`

This probably creates issues running other nf-core pipelines on Irma as well.

**Comment by maxulysse** [comment]
ok, so I'm assuming that this PR broke it: https://github.com/nf-core/configs/commit/ac815ce790690754807fbcab1f52444868350d7e

Am I right into assuming that this commit is the last one valid for this config?
https://github.com/nf-core/configs/tree/ff20f121f952a731b93f5719bc2006956117b9c1

Can we download a specific tag of nf-core/configs with nf-core/tools download? like when we use pipelines with `--custom_config_base https://raw.githubusercontent.com/nf-core/configs/ff20f121f952a731b93f5719bc2006956117b9c1`?
That should actually do the trick

**Comment by ewels** [comment]
This comes from the recent merge of #226 from @pontus - it looks like the logic misses Irma, which we just found out about the hard way after our latest deployment of nf-core pipelines.

I think that it basically comes down to this code needing a `<=` instead of `<`:
https://github.com/nf-core/configs/blob/5afa43ad1534d526b4179b20adc598b1de947e63/conf/uppmax.config#L31-L33

Maximum memory jobs  end up requesting exactly 250: https://github.com/nf-core/configs/blob/5afa43ad1534d526b4179b20adc598b1de947e63/conf/uppmax.config#L72-L74

And so they miss that clause and run through to the end, asking for 512 instead.

**Comment by maxulysse** [comment]
I think the underlying issue would be that we would need to be able to download a specific tag/branch/commit whatever with tools, because Sarek 2.7 broke and it was working before.
This is bad for production, we do need to be be able to use fixed config files as well without problem.
I know it's easy when online, but more complicated offline.
I'll raise an issue on nf-core tools for that.

**Comment by pontus** [comment]
:facepalm: 

That's obviously wrong with setting that explicitly as done.

(I'm a bit confused about how your actual issue came about, though, was this a normal increasing retry or do you have custom configuration to set memory to 250 Gbyte?)

**Comment by pontus** [comment]
And now I'm even more intrigued, irma should be handled by https://github.com/nf-core/configs/blob/5afa43ad1534d526b4179b20adc598b1de947e63/conf/uppmax.config#L27 and falling out there already (I wonder if that's not acceptable form for a regexp).

Obviously, the limit should be okay, but I wonder if that's what caused your disruption.

**Comment by alneberg** [comment]
@pontus I agree with you, I think the hostname catch should work. Could it be that `return base` returns something which is not valid for irma slurm?

**Comment by maxulysse** [comment]
Is this returning irma on irma?
https://github.com/nf-core/configs/blob/5afa43ad1534d526b4179b20adc598b1de947e63/conf/uppmax.config#L18

**Comment by ewels** [comment]
> I'm a bit confused about how your actual issue came about, though, was this a normal increasing retry or do you have custom configuration to set memory to 250 Gbyte?

@pontus its any process that requests more than that, as that's our `params.max_memory` value. In this case it was the Sarek pipeline that has a process that explicitly requests `params.max_memory` (via a label called "max_memory"). But yeah I guess there are probably other mega processes out there.

**Comment by ewels** [comment]
Yeah needs some debugging on Irma to see what is being returned with the hostname call. Not at a computer now but maybe someone else can have a go? Or I can try tomorrow.

**Comment by alneberg** [comment]
@maxulysse the command returns `i1` on irma, but it occassionally reports `grep: write error`. More specifically I don't see the message when I'm on tmux, but I do see it outside of tmux. Not sure if it matters or why that is.

**Comment by maxulysse** [comment]
> @maxulysse the command returns `i1` on irma, but it occassionally reports `grep: write error`. More specifically I don't see the message when I'm on tmux, but I do see it outside of tmux. Not sure if it matters or why that is.

Is there any chance that this happened during the deployment and then caused the issue?

**Comment by ewels** [comment]
> Is there any chance that this happened during the deployment and then caused the issue?

That command is executed at pipeline run time, not download.

**Comment by ewels** [comment]
The `grep: write error` thing is something to do with the piped commands, that grep keeps throwing out results even after the `head` command stops taking them I think. We should be able to fix this by telling `grep` to only return one match with `-m 1` and then we can drop the `head` bit completely:

```bash
sinfo --local -N -h | grep -m 1 -F -v CLUSTER: | cut -f1 -d' '
```

@alneberg this fixes the error you saw for me. Would be good if you could also confirm 👍🏻 

I'll stick in a PR now.
