### ISSUE TITLE
Request: Lund University Profile `aurora` HPC

### ISSUE THREAD

**Issue by stela2502** [nf-core/configs#292]
# nf-core/scrnaseq feature request

Hi nf-core/scrnaseq developer!

I got interested in your very promising package and am trying to set it up on aurora - our HPC system in Lund.

This system (aurora) uses /projects as mount point for the storage. When using singularity container to store and run the analysis software I can not access my data if I do not "mount" this path inside the container. To do so I would need a /projects path in the singularity container and this path would also need to be actively filled (-B /projects:/projects) in the singularity startup.

I think this is a very simple fix - just I am not familiar with nextflow. Is there a configuration that enables me to do this or do you need to change the singularity image in order to become compatible with the Lund University HPC system? 

Thank you for your time and help!

**Comment by jfy133** [comment]
I will take this as a no so closing. Feel free to re-open if necessary
