### ISSUE TITLE
how can I contact you for help via slack - 2 different gmail addresses not accepted

### ISSUE THREAD

**Issue by claus-h-g** [nf-core/configs#302]
hello,
what is the trick to obtain help from you via slack. I tried to join  the nf-core on slack under https://nfcore.slack.com/
choose continue with google  and ended up with the message:
"The email address must match one of the domains listed below. Please try another email." 
I can not the workspace administrator at nf-core for an invitation either.
Please suggest a working way for joining the nf-core on slack.
Many Thanks & looking forward to reading from you.

**Comment by ewels** [comment]
Hi @claus-h-g,

Did you try following the link on https://nf-co.re/join ? The following should take you to an invite page where you can sign up with any email address: https://nf-co.re/join/slack

Phil

**Comment by claus-h-g** [comment]
Just did - thanks. I did not see any redirection to this page on the page I was redirected to from github (https://nfcore.slack.com/channels/configs).
Thanks
Claus
