### ISSUE TITLE
imperial_mb.config

### ISSUE THREAD

**Issue by Al-Murphy** [nf-core/configs#318]
Hey,

Not sure if you are aware but the large med-bio queue (as used in the imperial_mb.config) has been deprecated but annoyingly you can still submit jobs to it and they will just stay queued.

Alan.

**Comment by Al-Murphy** [comment]
Not sure if you are aware @combiz

**Comment by apeltzer** [comment]
I just stumbled upon this, and see #645 for another report as well as my attempt using the public documentation in #646 to fix it for you. Mind testing? ;-)
