### ISSUE TITLE
Show documentation on the website

### ISSUE THREAD

**Issue by ewels** [nf-core/configs#343]
It would be good to either move or render the documentation in this repo on the main nf-core website somehow.

The stuff on the readme is quite good and general, and the docs for the profiles are very difficult to find.

Maybe a new subsection of the website dedicated for institutional configs?

**Comment by Emiller88** [comment]
Just gonna leave this here...

 https://www.gatsbyjs.com/plugins/gatsby-source-filesystem/#createremotefilenode

**Comment by jfy133** [comment]
it would be also nice to give 'reviewing guidelines' like for modules. Makes it much easier to review to get basic stuff right :+1:

**Comment by maxulysse** [comment]
This issue is a duplicate of https://github.com/nf-core/nf-co.re/issues/229

**Comment by jfy133** [comment]
Closing in favour of the nf-core website one as it's more relevant there :)
