### ISSUE TITLE
Documentation: UPPMAX nf-core modules

### ISSUE THREAD

**Issue by ewels** [nf-core/configs#345]
On the Swedish UPPMAX clusters you can now do `modules load nf-core-pipelines` to get access to pre-downloaded and cached pipelines complete with their singularity containers.

This is basically undocumented currently, it would be great to add mention of it to the configs UPPMAX docs. It is now the recommended way to run nf-core pipelines on UPPMAX (especially offline clusters, eg. Bianca)

**Comment by brainfo** [comment]
Hi, I'm a Bianca user and I cannot get into the nfcore UPPMAX slack channel. How could I get into it? Just in case I will encounter any problems.
Thanks!

**Comment by Aratz** [comment]
I'd like to work on this :raising_hand:
