### ISSUE TITLE
MPCDF Nodes (Raven) memory logic needs to be improved for shared nodes 

### ISSUE THREAD

**Issue by jfy133** [nf-core/configs#383]
I was running nf-core/mag with `-profile mpcdf,raven,test_full` and was getting failed to execute to grid schedular.

Manually submitting the failed job resulted in

```
sbatch: error: job memory limit for shared nodes exceeded. Must be <= 120000 MB
sbatch: error: Batch job submission failed: Invalid feature specification
```

We need to play with settings to correctly set this.

**Comment by jfy133** [comment]
Basically need to ensure if jobs go above the `shared` node configuration, it switches to the _minimum_ requirements for the exclusive nodes.

i.e., you go above 

```
    shared    cpu     36 / 72  in HT mode                     120 GB          < 1       24:00:00
```

either 36 cores OR 120 Gb, you must go to a MINIMUM

```
    exclusive cpu     72 / 144 in HT mode                     240 GB         1-360      24:00:00
```

of 72 cores AND 240 GB memory

**Comment by jfy133** [comment]
Also seems to be a `maxFork` limit of 16 jobs on exclusive nodes

**Comment by maxulysse** [comment]
Have you tried: `-profile test_full,mpcdf,raven`?
