### ISSUE TITLE
[IMPERIAL CONFIG] Not working anymore

### ISSUE THREAD

**Issue by SethMagnusJarvis** [nf-core/configs#645]
I've been trying to run the smrnaseq pipeline on the HPC. It doesn't work if I try to use the imperial profile. The error I get is relating to job sizing/resource selection. When I looked at the file, it turned out that the job was being submitted larger than the HPC can handle, and with a submission time of 0. The pipeline works fine if I just run it on one large node.

**Comment by jfy133** [comment]
Hi @SethMagnusJarvis , you would need to ask @combiz who apparently made the imperial profile.

Also it would be helpful to have the command you tried and which 'file' you used.

Note that only people in your institution can check/debug the profile, so support from others will be limited. But we can see what we can do.

**Comment by SethMagnusJarvis** [comment]
I'm a muppet and thought that this would post a comment directly on the imperial config.

I was wondering if there was anything obviously wrong with the imperial config (some of the options don't seem to have submission times as an example).

```
#!/usr/bin/bash

#PBS -lselect=1:ncpus=4:mem=16gb
#PBS -lwalltime=72:00:00

# Assume $HOME is:
# /rds/general/user/smj/home

# iGenomes:
# https://emea.support.illumina.com/sequencing/sequencing_software/igenome.html

# Params:
# https://nf-co.re/smrnaseq/parameters


source ~/.bash_profile
source $HOME/miniconda3/miniconda.sh
conda activate env_nf
NFDIR= $HOME/project

cd $NFDIR

nextflow run nf-core/smrnaseq \
-profile imperial,singularity \
-resume \
--input $NFDIR/samplesheet.csv \
--outdir $NFDIR/out \
--skip_mirdeep 0 \
--protocol custom \
--clip_r1 1 \
--three_prime_adapter TGGAATTCTCGGGTGCCAAGG \
--fastp_min_length 15 \
--fastp_max_length 28 \
--genome GRCm38
```

The file I looked at which seemed to show these sizing issues was:
$NFDIR/work/85/164fbca71130f6a4b36bba22106a98/.command.run

**Comment by apeltzer** [comment]
a.) Usually the profile handles stuff like singularity too, e.g. in the imperial profile its already activated - see https://github.com/nf-core/configs/blob/76074e48c049b2f37f2000ec30dd776035cd1d72/conf/imperial.config#L110-L114 that its active.
b.) If things break / are not up2date anymore, we can update the profile to make it work (again)

I am not sure this here is necessary at all - 

```
#!/usr/bin/bash

#PBS -lselect=1:ncpus=4:mem=16gb
#PBS -lwalltime=72:00:00

# Assume $HOME is:
# /rds/general/user/smj/home

# iGenomes:
# https://emea.support.illumina.com/sequencing/sequencing_software/igenome.html

# Params:
# https://nf-co.re/smrnaseq/parameters


source ~/.bash_profile
source $HOME/miniconda3/miniconda.sh
conda activate env_nf
NFDIR= $HOME/project
```

Particularly the PBS config stuff in the begining is  likely non-necessary / maybe even interferring with your submissions. Consider having a plain bash script that uses your profile without setting anything-  does that work? 

```
nextflow run nf-core/smrnaseq \
-profile imperial\
-resume \
--input $NFDIR/samplesheet.csv \
--outdir $NFDIR/out \
--skip_mirdeep FALSE \
--protocol custom \
--clip_r1 1 \
--three_prime_adapter TGGAATTCTCGGGTGCCAAGG \
--fastp_min_length 15 \
--fastp_max_length 28 \
--genome GRCm38
```

I looked at the config https://icl-rcs-user-guide.readthedocs.io/en/latest/hpc/queues/how-it-works/ page but couldn't find too much on it, the profile *should* still work. The submission times are sent by the config of smrnaseq, as its a *per task* time request, so the imperia lconfig only defines upper limits of whats available. 

However, the names of the requested queues seem not to fit anymore (?). The config requests e.g. https://github.com/nf-core/configs/blob/76074e48c049b2f37f2000ec30dd776035cd1d72/conf/imperial.config#L64 "v1_medium72" but the docs on the imperial college page show "medium72" as a name. That means we'd have to update at least the config to have the appropriate queues again, then things should be fine again.

**Comment by SethMagnusJarvis** [comment]
Okay, having done some testing and spoken to people:

The smallest change is that adding .h to line 43 (time   = { 8.h * task.attempt  }) seems to solve it. It works with the exusting queue names.

You can also remove all of the queue names and it works fine. The HPC actually specify that you don't need to include queue names.

I have been told that [combiz](https://github.com/combiz) is no longer at the university so probably shouldn't be point of contact. If they aren't necessary, removing that piece of informatoin would be useful.

**Comment by jfy133** [comment]
I'm guessing https://github.com/nf-core/configs/pull/646 will also close this as well
