### ISSUE TITLE
Problems to run nextflow command for fungus taxonomy

### ISSUE THREAD

**Issue by Juan-Andres-cmd** [nf-core/configs#734]
when I run my command it appears: 

Can't stage file https://files.plutof.ut.ee/public/orig/1E/25/1E25CA4CC30A31C2E2B8CB2C89824C83D080A7F5A62E6263A0E95B37C6628067.tgz -- reason: Unable to access path: https://files.plutof.ut.ee/public/orig/1E/25/1E25CA4CC30A31C2E2B8CB2C89824C83D080A7F5A62E6263A0E95B37C6628067.tgz

I am running the following command: nextflow run nf-core/ampliseq -r 2.10.0 -profile docker --input "sample_sheet.tsv" --FW_primer GGAAGTAAAAGTCGTAACAAGG --RV_primer GCTGCGTTCTTCATCGATGC --illumina_pe_its --min_frequency 2 --dada_ref_taxonomy "unite-fungi" --max_memory '60.GB' --outdir "fungi_out"

**Comment by jfy133** [comment]
I @Juan-Andres-cmd please ask on https://github.com/nf-core/ampliseq, as your question does not appear to be related to nf-core/configs
