### ISSUE TITLE
BinAC Multiple queue logic

### ISSUE THREAD

**Issue by apeltzer** [nf-core/configs#75]
```
process.queue = { task.memory > 756.GB ? 'supercruncher': task.time <= 2.h ? 'short' : task.time <= 48.h ? 'medium': 'long' }
```

**Comment by d4straub** [comment]
Tested, improved with e.g. #117 and works.

`queue = { task.memory >= 128.GB ? 'smp': task.time <= 20.m ? 'tiny' : task.time <= 48.h ? 'short' : task.time <= 168.h ? 'short' : 'long'}`

Probably `tiny` isnt yet perfect, also max 4 cpus, but who is using more than 4 cpu for 20 min anyway.
