### ISSUE TITLE
Tutorial in docs not available

### ISSUE THREAD

**Issue by vdejager** [nf-core/configs#812]
I am about to create a profile for our local HPC, but encountered a 404 on the tutorial

https://nf-co.re/docs/usage/tutorials/step_by_step_institutional_profile

Best Vic

**Comment by jfy133** [comment]
@vdejager where did you find that link? https://nf-co.re/docs/tutorials/use_nf-core_pipelines/writing_institutional_profiles

**Comment by jfy133** [comment]
Ah I found it: https://nf-co.re/docs/usage/getting_started/configuration#shared-nf-coreconfigs

Fixing!
